version: '3.8'

services:
  speedtest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: speedtest-app
    ports:
      - "8080:8080"
    environment:
      - BIND_ADDRESS=0.0.0.0
      - PORT=8080
      - LOG_LEVEL=info
    env_file:
      - config.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - speedtest-network

networks:
  speedtest-network:
    driver: bridge
